### ISSUE TITLE
Добавить README.md

### ISSUE THREAD

**Issue by Znack** [Burize/FULLSTACK-GameOfLife#2]
Описать все подробно команды, чтобы запустить проект у себя. Лучше еще при этом проверить с чистого листа, что только этих команд достаточно для запуска

**Comment by Znack** [comment]
И можешь там описать свою архитектуру, почему какие ограничения ты ввел и какие соглашения соблюдать программисту, который будет за тобой код поддерживать?

**Comment by Burize** [comment]
Опишу в последнюю очередь, после закрытия других issue.

**Comment by Znack** [comment]
Так нам разворачивать надо как-то, я еще не пробовал даже у себя запустить :)

**Comment by Znack** [comment]
Ну и понимание архитектуры хотелось бы тоже оценить уже сейчас

**Comment by Burize** [comment]
Пока не очень понимаю, что написать. 

Для запуска нужно запустить только "npm i" и "npm start".
Для тестирования "npm test".

"И можешь там описать свою архитектуру, почему какие ограничения ты ввел и какие соглашения соблюдать программисту, который будет за тобой код поддерживать?" - Используется MVC шаблон. Весь код валидируется ESLint, который проверяет все перед сборкой. Для него используется конфиг от airBnB. Вооот ... но этого наверное не достаточно.

"Ну и понимание архитектуры хотелось бы тоже оценить уже сейчас" - как- то расписать MVC на примере этого проекта?

**Comment by Znack** [comment]
> как- то расписать MVC на примере этого проекта?

да-да, опиши, какие прицнипы ты и как использовал. Описывай потом по ходу еще новые детали (например, я в другом ишью написал, что хэндлеры через методы лучше делать), и описывай почему именно так

**Comment by Znack** [comment]
Ну и 
> Для запуска нужно запустить только "npm i" и "npm start". Для тестирования "npm test".

вот это и помести как раз в начало :)
