### ISSUE TITLE
По стандартам сложные условия выносить функции

### ISSUE THREAD

**Issue by Znack** [Burize/FULLSTACK-GameOfLife#5]
Есть условия сложнее одного оператора, их в отдельные функции

**Comment by Burize** [comment]
Нашел 2 таких условия. И они хорошо описывают мой вопрос: в любых случаях если больше 1 оператора выносить в одну функцию?

Например, в контроллере в функции endGame() проверяется равенство по длине двумерных массивов (квадратных)

       endGame(currentField) {
    if (this._previousField.length !== currentField.length || this._previousField[0].length !== currentField[0].length) {
      this._previousField = currentField;
      return false;
     }

      ***
    }
Вынес условие в отдельную функции. Теперь у меня есть функция, выполняющая определенное действие (то есть ясно для чего она), которую можно еще где-нибудь использовать и код внутри endGame() стал более читабельным.  

В этом случае понятно зачем это.

А вот в следующей функции тоже нужно выносить в отдельную функцию (второй if)?

       updateCells() {
    this._cells = this._cells.map((line, x) => line.map((cell, y) => {
      const neighbors = this.countNeighbors(x, y);

      if (neighbors === 3) return new Cell(true);

      if (neighbors === 2 && cell.alive === true) return new Cell(true);

      return new Cell();
    }));

    return JSON.parse(JSON.stringify(this._cells));
    }

Тут два условия, они максимально примитивны. Если делать функцию с ними, то навряд ли ее можно будет использовать где-нибудь еще, и не понятно как ее назвать. По сути этот if является частью проверки состояния клетки, которая состоит из двух if-ов.  Если выносить их оба (оба условия) в отдельную функцию, то тоже странно, ведь обработчик для map состоит почти только из них. Поэтому пока оставил без изменений 2ой случай.

**Comment by Znack** [comment]
На самом деле второй вариант еще более логичным кажется вынести, причем оба условия можно вынести вместе и объединить через OR, тогда не надо будет два раза код создания клетки повторять. А название у функции поможет в дальнейшем легко понять, что это за условие. С названием помогать не буду, тебе надо самому как раз его придумать максимально понятным, прозрачным и недвусмысленным :)
